# Generated by Django 3.1.6 on 2021-07-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='fullAddress',
            field=models.CharField(blank=True, default='', max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='postcode',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='review',
            name='areaBenefits',
            field=models.CharField(blank=True, help_text='What were the benefits of the area?', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='areaPerks',
            field=models.CharField(blank=True, help_text='Perks of area', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='bedroomQualityComment',
            field=models.CharField(blank=True, help_text='Can you explain why you have given it the rating that you have?', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='buildigComment',
            field=models.CharField(blank=True, help_text='Can you explain why you have given it the rating that you have?', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='email',
            field=models.CharField(blank=True, help_text='email', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='employmentStatus',
            field=models.CharField(choices=[('Student', 'Student'), ('Employed', 'Employed'), ('Self-Employed', 'Self-Employed')], default='Student', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='furnishingsComment',
            field=models.CharField(blank=True, help_text='Can you explain why you have given it the rating that you have?', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='hiddenExpenses',
            field=models.CharField(blank=True, help_text='Were there any hidden expenses at the end of the tenancy? (Cleaning costs, significant deposit reductions, unexpected charges, etc) ', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='landlordComments',
            field=models.CharField(blank=True, help_text='LANDLORD: Any other comments', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='likedLeast',
            field=models.CharField(blank=True, help_text='What do/did you like least about the property?', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='likedMost',
            field=models.CharField(blank=True, help_text='What do/did you like most about the property?', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='manageResponsivenesComment',
            field=models.CharField(blank=True, help_text='Can you explain why you have given them the rating that you have?', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='moveInHygeneComment',
            field=models.CharField(blank=True, help_text='Can you explain why you have given it the rating that you have?', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='neighbourhoodDescription',
            field=models.CharField(blank=True, help_text='How would you describe the neighbourhood to someone thinking of living there?', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='neighbourhoodSafetyComment',
            field=models.CharField(blank=True, help_text='Can you explain why you have given it the rating that you have?', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='qualityComments',
            field=models.CharField(blank=True, help_text='Any other comment about the quality of property?', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='repairQualityComment',
            field=models.CharField(blank=True, help_text='Can you explain why you have given it the rating that you have?', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewerName',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='timeStamp',
            field=models.CharField(blank=True, help_text='Time data was collected', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='utilitiesComment',
            field=models.CharField(blank=True, help_text='Can you explain why you have given it the rating that you have?', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='wantedToKnowBefore',
            field=models.CharField(blank=True, help_text='Is there anything else you would have liked to have known about the property manager before you moved in?', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='whoSentSurvey',
            field=models.CharField(blank=True, help_text='Who sent you this survey? (Leave blank if you scanned the QR code on our leaflet)', max_length=500, null=True),
        ),
    ]
