# Generated by Django 3.1.6 on 2021-06-23 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beta', '0002_auto_20210622_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='ambassadorPotential',
            field=models.BooleanField(default=True, help_text='Would you like to be sent paid opportunities to be a GuaRENTeed ambassador?', null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='bedroomNumber',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=3, help_text='How many bedrooms was the house? ', null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='bedroomQuality',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3, help_text='What is the quality of the bedrooms at the property? (Size, comfort, privacy etc)', null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='buildingQuality',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3, help_text='How would you rate the quality of the building (considering mould, pests, cleanliness, damp, etc.)?', null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='contactWhenDataPublic',
            field=models.BooleanField(default=True, help_text='Would you like to be contacted when this review is made public?', null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='cosyInWinter',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3, help_text='It was cosy in the winter', null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='dataConsent',
            field=models.BooleanField(default=True, help_text='Are you happy for the data collected during this interview to appear anonymously as a property review on our website?', null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='easyToSleepAtNight',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3, help_text='It was easy to sleep at night', null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='employmentStatus',
            field=models.CharField(choices=[('Student', 'Student'), ('Employed', 'Employed'), ('Self-Employed', 'Self-Employed')], default='Student', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='enjoyedCooking',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3, help_text='I enjoyed cooking in the kitchen', null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='feltLikeAHome',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3, help_text='It felt like a home', null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='feltSafe',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3, help_text='I felt safe in my house', null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='furnishings',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3, help_text='If the property was furnished, what is the quality of the furnishings like? (Beds, wardrobes, tables, sofas, etc.)', null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='futuePaidWork',
            field=models.BooleanField(default=True, help_text='Would you like to hear about future opportunities to work as a paid ambassador for GuaRENTeed?', null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='goodPlaceForDinnerParties',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3, help_text='My house was a good place to have dinner parties', null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='goodPlaceForFriends',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3, help_text='My house was a good place to have friends over', null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='hotShower',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3, help_text='I was able to have a hot shower whenever I wanted', null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='landlordRating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3, help_text='LANDLORD: Any other comments', null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='landlordRelationship',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3, help_text='I had a good relationship with my landlord / estate agent', null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='maintenanceMoveIn',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3, help_text='MAINTENANCE/CONDITION: How would you rate the condition of the property when you moved in?', null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='manageResponsivenes',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3, help_text='When you have a problem how responsive is the property manager? ', null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='moveInHygene',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3, help_text='When you moved in, how clean was the property?', null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='neighbourhoodEnjoyment',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3, help_text='How much do you enjoy living in this area?', null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='neighbourhoodSafety',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3, help_text='How safe do you feel in the neighbourhood?', null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='neighboursRelationship',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3, help_text='I had a good relationship with my neighbours', null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='overallRating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3, help_text='Overall, how would you rate this property?', null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='rentMonthly',
            field=models.PositiveIntegerField(default=500, help_text='What is the total monthly rent for the property?', null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='repairQuality',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3, help_text='When the property manager arranges a repair, the repair is usually...', null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewerName',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='study',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3, help_text='It was good for studying and focus', null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='timeStamp',
            field=models.CharField(blank=True, help_text='Time data was collected', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='utilities',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3, help_text='How would you rate the utilities? (water pressure, heating, insulation etc)', null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='whiteGoods',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3, help_text='MAINTENANCE/CONDITION: What was the quality of the white goods (dishwasher, washing machine etc)', null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='windowView',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3, help_text='I enjoyed the view out of the windows', null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='wouldRecommendProperty',
            field=models.BooleanField(default=True, help_text='Would you reccomend this property to others? ', null=True),
        ),
    ]
