# Generated by Django 3.1.6 on 2021-06-23 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beta', '0003_auto_20210623_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='livingConfirmation',
            field=models.BooleanField(blank=True, default=True, help_text='Do you confirm that you live or lived at the property in question?'),
        ),
    ]
