# Generated by Django 3.1.6 on 2021-06-23 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beta', '0004_auto_20210623_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='moveInHygene',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3, help_text='When you moved in, how clean was the property?', null=True),
        ),
    ]
