# Generated by Django 3.1.6 on 2021-06-23 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beta', '0005_auto_20210623_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='moveIn',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='moveOut',
            field=models.DateField(null=True),
        ),
    ]
