# Generated by Django 3.1.6 on 2021-06-24 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beta', '0006_auto_20210623_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='landlordRating',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3, help_text='LANDLORD: Any other comments', null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='maintenanceMoveIn',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3, help_text='MAINTENANCE/CONDITION: How would you rate the condition of the property when you moved in?', null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='whiteGoods',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3, help_text='MAINTENANCE/CONDITION: What was the quality of the white goods (dishwasher, washing machine etc)', null=True),
        ),
    ]
