# Generated by Django 3.1.6 on 2021-06-24 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beta', '0007_auto_20210624_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='bedroomNumber',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=3, help_text='How many bedrooms was the house? ', null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='bedroomQuality',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3, help_text='What is the quality of the bedrooms at the property? (Size, comfort, privacy etc)', null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='buildingQuality',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3, help_text='How would you rate the quality of the building (considering mould, pests, cleanliness, damp, etc.)?', null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='cosyInWinter',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3, help_text='It was cosy in the winter', null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='easyToSleepAtNight',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3, help_text='It was easy to sleep at night', null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='enjoyedCooking',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3, help_text='I enjoyed cooking in the kitchen', null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='feltLikeAHome',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3, help_text='It felt like a home', null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='feltSafe',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3, help_text='I felt safe in my house', null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='furnishings',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3, help_text='If the property was furnished, what is the quality of the furnishings like? (Beds, wardrobes, tables, sofas, etc.)', null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='goodPlaceForDinnerParties',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3, help_text='My house was a good place to have dinner parties', null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='goodPlaceForFriends',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3, help_text='My house was a good place to have friends over', null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='hotShower',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3, help_text='I was able to have a hot shower whenever I wanted', null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='landlordRelationship',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3, help_text='I had a good relationship with my landlord / estate agent', null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='manageResponsivenes',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3, help_text='When you have a problem how responsive is the property manager? ', null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='neighbourhoodEnjoyment',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3, help_text='How much do you enjoy living in this area?', null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='neighbourhoodSafety',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3, help_text='How safe do you feel in the neighbourhood?', null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='neighboursRelationship',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3, help_text='I had a good relationship with my neighbours', null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='overallRating',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3, help_text='Overall, how would you rate this property?', null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='repairQuality',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3, help_text='When the property manager arranges a repair, the repair is usually...', null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='study',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3, help_text='It was good for studying and focus', null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='utilities',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3, help_text='How would you rate the utilities? (water pressure, heating, insulation etc)', null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='windowView',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3, help_text='I enjoyed the view out of the windows', null=True),
        ),
    ]
