# Generated by Django 3.1.6 on 2021-07-05 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beta', '0009_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
